# Generated by Django 2.0.5 on 2018-05-11 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
            ('main', '0001_initial'),
            ]

    operations = [
            migrations.RemoveField(
                model_name='calendar',
                name='id',
                ),
            migrations.AddField(
                model_name='calendar',
                name='calendar_id',
                field=models.CharField(default='', max_length=255, primary_key=True, serialize=False),
                preserve_default=False,
                ),
            migrations.AddField(
                model_name='calendar',
                name='provider',
                field=models.CharField(default='', max_length=255),
                preserve_default=False,
                ),
            migrations.AddField(
                model_name='calendar',
                name='refresh_token',
                field=models.CharField(default='', max_length=255),
                preserve_default=False,
                ),
            ]
