# Generated by Django 2.0.5 on 2018-05-12 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
            ('main', '0002_auto_20180511_0330'),
            ]

    operations = [
            migrations.AddField(
                model_name='item',
                name='family',
                field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Family'),
                preserve_default=False,
                ),
            migrations.AlterUniqueTogether(
                name='item',
                unique_together={('institution_id', 'family')},
                ),
            ]
