# Generated by Django 2.0.5 on 2018-05-12 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20180512_1905'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('address', 'city', 'state', 'zip', 'lon', 'lat')},
        ),
    ]
