# Generated by Django 2.0.5 on 2018-05-15 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
            ('main', '0009_item_user'),
            ]

    operations = []
