# Generated by Django 2.0.5 on 2018-05-15 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20180515_0446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='family',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Family'),
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('institution_id', 'user')},
        ),
    ]
