# Generated by Django 2.0.5 on 2018-05-15 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20180515_0450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='family',
        ),
        migrations.AlterField(
            model_name='user',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Family'),
        ),
    ]
