# Generated by Django 2.0.5 on 2018-05-19 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20180515_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='track',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
