# Generated by Django 2.0.5 on 2018-05-25 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20180521_0236'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmountRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(choices=[('EQ', '='), ('GT', '>'), ('GTE', '≥'), ('LT', '<'), ('LTE', '≤')], max_length=20)),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DateRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repeats_every_num', models.IntegerField(default=1)),
                ('repeats_every_type', models.CharField(choices=[('DAY', 'day'), ('WEEK', 'week'), ('MONTH', 'month')], max_length=20)),
                ('day_of_week', models.IntegerField(blank=True, choices=[(1, 'Sunday'), (2, 'Monday'), (3, 'Tuesday'), (4, 'Wednesday'), (5, 'Thursday'), (6, 'Friday'), (7, 'Saturday')], null=True)),
                ('day_of_month', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NameRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(choices=[('CONTAINS', 'contains (case sensitive)'), ('ICONTAINS', 'icontains (case insensitive)'), ('EXACT', 'exact (case sensitive)'), ('IEXACT', 'iexact (case insensitive)'), ('STARTSWITH', 'startswith (case sensitive)'), ('ISTARTSWITH', 'istartswith (case insensitive)'), ('ENDSWITH', 'endswith (case sensitive)'), ('IENDSWITH', 'iendswith (case insensitive)')], max_length=20)),
                ('value', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RuleSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Item')),
            ],
        ),
        migrations.AlterField(
            model_name='transaction',
            name='name',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='namerule',
            name='rule_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.RuleSet'),
        ),
        migrations.AddField(
            model_name='daterule',
            name='rule_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.RuleSet'),
        ),
        migrations.AddField(
            model_name='amountrule',
            name='rule_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.RuleSet'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='rule_set',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.RuleSet'),
        ),
    ]
