# Generated by Django 2.0.5 on 2018-05-28 19:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20180525_0546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daterule',
            name='day_of_month',
        ),
        migrations.RemoveField(
            model_name='daterule',
            name='day_of_week',
        ),
        migrations.AddField(
            model_name='daterule',
            name='day_range_buffer',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='daterule',
            name='starting_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='daterule',
            name='repeats_every_type',
            field=models.CharField(choices=[('DAY', 'day'), ('MONTH', 'month')], max_length=20),
        ),
        migrations.AlterField(
            model_name='namerule',
            name='operator',
            field=models.CharField(choices=[('CONTAINS', 'contains (case sensitive)'), ('EXACT', 'exact (case sensitive)'), ('STARTSWITH', 'startswith (case sensitive)'), ('ENDSWITH', 'endswith (case sensitive)')], max_length=20),
        ),
    ]
