# Generated by Django 2.0.5 on 2018-06-03 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20180528_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruleset',
            name='calendar_event_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ruleset',
            name='last_transaction_amount',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='ruleset',
            name='last_transaction_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ruleset',
            name='predicted_next_transaction_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
