# Generated by Django 2.0.5 on 2018-06-04 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20180603_2053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='location',
        ),
        migrations.AlterField(
            model_name='namerule',
            name='operator',
            field=models.CharField(choices=[('CONTAINS', 'contains (case isensitive)'), ('EXACT', 'exact (case isensitive)'), (
                'STARTSWITH', 'startswith (case isensitive)'), ('ENDSWITH', 'endswith (case isensitive)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ruleset',
            name='last_transaction_amount',
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
