# Generated by Django 2.0.5 on 2018-06-09 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_amountrule_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amountrule',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
