# Generated by Django 2.0.5 on 2018-07-01 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20180609_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daterule',
            name='rule_set',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='date_rule_info', to='main.RuleSet'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='rule_set',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='main.RuleSet'),
        ),
    ]
