# Generated by Django 2.0.5 on 2018-08-19 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20180701_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='rule_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='main.RuleSet'),
        ),
    ]
